name: solari
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  get_it: ^8.0.3
  shared_preferences: ^2.4.0
  dio: ^5.7.0
  dio_smart_retry: ^7.0.1
  firebase_core: ^3.10.1
  firebase_notifications_handler: ^2.0.2
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  sentry_flutter: ^8.12.0
  bot_toast: ^4.1.3
  flutter_bloc: ^9.0.0
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.10
  connectivity_plus : ^6.1.2
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0
flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
