name: solari
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  get_it: ^8.0.3
  shared_preferences: ^2.4.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  firebase_core: ^3.10.1
  firebase_notifications_handler: ^2.0.2+1
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  sentry_flutter: ^8.14.2
  bot_toast: ^4.1.3
  flutter_bloc: ^9.1.0
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  connectivity_plus : ^6.1.3
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.1.1
  flutter_animate: ^4.5.2
  app_settings: ^6.1.1
  fl_chart: ^0.71.0
  geolocator: ^13.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab/RobotoSlab-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Medium.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Regular.ttf
          weight: 500
        - asset: assets/fonts/RobotoSlab/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab/RobotoSlab-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Black.ttf
          weight: 900
