// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvhJkNS6VFYnK1MiZE5HnIJqA-dBv3KM8',
    appId: '1:741998073243:web:13c373f9d41dc50b49bd3e',
    messagingSenderId: '741998073243',
    projectId: 'solari-app',
    authDomain: 'solari-app.firebaseapp.com',
    storageBucket: 'solari-app.firebasestorage.app',
    measurementId: 'G-5BGP0LR0WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvmF23HcDUZ-x3tahR1WeL1s1MvjsPhPM',
    appId: '1:741998073243:android:658690c189534ef349bd3e',
    messagingSenderId: '741998073243',
    projectId: 'solari-app',
    storageBucket: 'solari-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyPJ_ZAd7vZgJk64bpSKZ29dJCIJE_as4',
    appId: '1:741998073243:ios:efee0e68e3e7504f49bd3e',
    messagingSenderId: '741998073243',
    projectId: 'solari-app',
    storageBucket: 'solari-app.firebasestorage.app',
    iosBundleId: 'com.example.solari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyPJ_ZAd7vZgJk64bpSKZ29dJCIJE_as4',
    appId: '1:741998073243:ios:efee0e68e3e7504f49bd3e',
    messagingSenderId: '741998073243',
    projectId: 'solari-app',
    storageBucket: 'solari-app.firebasestorage.app',
    iosBundleId: 'com.example.solari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvhJkNS6VFYnK1MiZE5HnIJqA-dBv3KM8',
    appId: '1:741998073243:web:ad166c9e9ede843849bd3e',
    messagingSenderId: '741998073243',
    projectId: 'solari-app',
    authDomain: 'solari-app.firebaseapp.com',
    storageBucket: 'solari-app.firebasestorage.app',
    measurementId: 'G-RREG9R6FYF',
  );
}
